### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by DenTelezhkin**
Hey, @zhxnlai and @AndrewSB!

Thanks for awesome framework, it has been very helpful in one of my projects! I wanted to help with migration to Swift 3. In this PR only framework is migrated, not example target, since Cartography and ReactiveUI pods are not Swift-3 ready yet. 

I would be happy to help with migration, if there's something else needed.

### CODE REVIEW

**Comment by AndrewSB** [comment]
Hey @DenHeadless, thank you for contributing!

This looks great 😄, if you target a new branch, `zhxnlai/swift3`, I'll go ahead and merge this, and then once Cartography and ReactiveUI vend swift 3 compatible pods, we can update the demo, merge into master, and create a new release!

How does that sound to you?

**Comment by DenTelezhkin** [comment]
Hey! That does sound great. Please create swift3 branch, and i'll retarget this PR to it. It seems i cant target PR to branch that is not present on your repo.

**Comment by AndrewSB** [comment]
created `swift3`

**Comment by DenTelezhkin** [comment]
Retargeted PR to swift3 👍

**Comment by AndrewSB** [comment]
🎉

**Pull request merged**
