### PR TITLE
fixed ViewManager.addTapRecognizer() for nil target gesture recognizer

### PR DESCRIPTION
**Pull request by oaleeapp**
#113 Fixed it temporarily, by remove previous tap gestures when it tends to add new tap gesture.

### CODE REVIEW

**Comment by AndrewSB** [comment]
can you add a description (and maybe a link to the issue you created) for why this is necessary directly to your commit message? If you aren't sure how to do that, I can help :)

**Comment by oaleeapp** [comment]
Sure, 
This pull request keen to fix the issue #113 , 
which the tap gesture's target will be `null` after rewinding the card.
Current approach just removes the previous tap gesture and add the new one.

**Comment by AndrewSB** [comment]
That's great @oaleeapp, but I meant adding it to the commit message directly, like https://github.com/facebook/ds2/pull/510/commits/35d866d95fb5df1ae93c59368de369289e84d583

**Comment by oaleeapp** [comment]
Ah, I see, I think I will need to amend the commit and submit again, right?

**Comment by AndrewSB** [comment]
Yup!

**Comment by oaleeapp** [comment]
Sorry for being late, I've modified the commit as the link below,

[b9f4d4b](https://github.com/oaleeapp/ZLSwipeableViewSwift/commit/b9f4d4b2fc04556534e6b5b5f3227657ef7bd8ec)

Not sure is it the correct format, can you help me out?

@AndrewSB

**Comment by AndrewSB** [comment]
Thanks @oaleeapp 😆

**Pull request merged**
