### PR TITLE
Carthage support + Swift 2 Compatibility 

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by AndrewSB** [comment]
Hey @zhxnlai, any chance this can be looked at soon?
If you're extremely busy I volunteer as helping manage this project, I've now used it in 3 apps and am pretty familiar with the API

**Comment by zhxnlai** [comment]
Thanks for offering! I have added you as a collaborator.

**Comment by AndrewSB** [comment]
Awesome :+1:

**Comment by zhxnlai** [comment]
Hi @AndrewSB. Do you use CocoaPods? I can add you to the pod owners.

**Pull request closed without merging**
